spring.application.name=studentmanager
spring.datasource.url=jdbc:sqlserver://den1.mssql8.gear.host:1433;databaseName=studentmannager;encrypt=true;trustServerCertificate=true
spring.datasource.username=studentmannager
spring.datasource.password=	Vongvotamquoc123@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

server.port=8081

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

spring.mvc.locale=vi_VN
spring.mvc.locale-resolver=fixed